version: '3.7'
services:
  frontend:
    container_name: frontend
    image: ghcr.io/sirmorfield/joppekoers.nl/frontend:latest
    restart: unless-stopped
    volumes:
      - ./frontend/static/img/projectImg:/app/build/client/img/projectImg
    ports:
      - 8080:8080

  cms:
    container_name: cms
    image: ghcr.io/sirmorfield/joppekoers.nl/cms:latest
    restart: unless-stopped
    volumes:
      - ./cms/public/uploads:/app/public/uploads
      - ./cms/db:/app/db
    env_file:
      - cms/.env
    environment:
      - PORT=133
    ports:
      - 1377:1377

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: frontend cms
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=30
      - WATCHTOWER_ROLLING_RESTART=true
