version: '3.7'
services:
  frontend:
    container_name: frontend
    build: .
    restart: unless-stopped
    volumes:
      - ./frontend/static/img/projectImg:/app/build/client/img/projectImg
      - ./frontend/static/uploads:/app/frontend/static/uploads
    environment:
      - PORT=8080
    ports:
      - 8080:8080
