name: Containerize

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_FRONTEND: ghcr.io/${{ github.repository }}/frontend
  IMAGE_NAME_CMS: ghcr.io/${{ github.repository }}/cms

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # can be removed if the user is the owner of the repository and the repository name are lowercase
      - name: Set lower case owner name
        run: |
          echo "IMAGE_NAME_FRONTEND=${IMAGE_NAME_FRONTEND,,}" >>${GITHUB_ENV}
          echo "IMAGE_NAME_CMS=${IMAGE_NAME_CMS,,}" >>${GITHUB_ENV}
        env:
          IMAGE_NAME_FRONTEND: "${{ env.IMAGE_NAME_FRONTEND }}"
          IMAGE_NAME_CMS: "${{ env.IMAGE_NAME_CMS }}"

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: .
          target: frontend
          push: true
          tags: ${{ env.IMAGE_NAME_FRONTEND }}

      - name: Build and push cms
        uses: docker/build-push-action@v4
        with:
          context: .
          target: frontend
          push: true
          tags: ${{ env.IMAGE_NAME_CMS }}
